name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        pydantic: ["==1.10.2", ">=2.0.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[test,server]' pydantic${{ matrix.pydantic }}

    - name: Lint with isort
      run: isort . --check

    - name: Lint with black
      run: black . --check

    - name: Run tests with pytest
      run: pytest --cov=autocoder --cov-report=term-missing
